#!/bin/sh

uci set system.@system[0].hostname='ROOter-Mesh-Wifi'
uci commit system
/etc/init.d/system restart

uci set network.lan.ipaddr="192.168.1.20"
uci commit network
/etc/init.d/network restart
