#!/bin/sh
. /lib/functions.sh

case "$ACTION" in
released)
	if [ "$SEEN" -gt 5 -a "$SEEN" -lt 15 ]
	then
		passwd -d root
		reboot -f
	fi
	if [ "$SEEN" -gt 15 -a "$SEEN" -lt 25 ]
	then
		passwd -d root
		uci set network.lan.ipaddr="192.168.1.1"
		uci commit network
		/etc/init.d/network restart
		reboot -f
	fi
;;
esac
return 0		

		