#!/bin/sh

uci set dhcp.lan.master='1'
uci set dhcp.lan.ra='hybrid'
uci set dhcp.lan.ra_flags='none'
uci set dhcp.lan.dhcpv6='hybrid'
uci set dhcp.lan.ra_management='1'
uci commit dhcp
/etc/init.d/dnsmasq restart
