#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=60

start() {
	WX=$(uci -q get custom.bwallocate.lock)
	if [ "$WX" = "1" ]; then
		uci set bwmon.general.enabled=1
		uci commit bwmon
	fi
	/usr/lib/bwmon/bwmon.sh &
}
