#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

START=88
USE_PROCD=1

log() {
	logger -t "Log Level" "$@"
}

start_service()
{
	uci set dhcp.odhcpd.loglevel='3'
	uci commit dhcp
	/etc/init.d/odhcpd restart
}