#!/bin/sh
#
# /etc/hotplug.d/iface/19-rooter
#
for I in `seq 1 $(uci get modem.general.modemnum)`
do
	IFACE="wan"$I

	[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0

	if [ ${INTERFACE} = "$IFACE" ]; then
		if [ ${ACTION} = "ifup" ]; then
			MTU=$(uci get modem.modeminfo$I.mtu)
			if [ -z $MTU ]; then
				MTU=1500
			fi
			if [ -n "$MTU" ]; then
				ip link set mtu $MTU dev $DEVICE
				logger -t "Custom MTU" $DEVICE set to $MTU
			fi
		fi
	fi
done
