#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Tomato >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Tomato=/luci-static/opentomato
		set luci.main.mediaurlbase=/luci-static/opentomato
		commit luci
	EOF
fi

exit 0
