#!/bin/sh /etc/rc.common

. /lib/functions.sh

START=99

log() {
	logger -t "Z-Hotspot " "$@"
}

start()
{
	PRO=$(uci get network.wwan.proto)
	if [ -z $PRO ]; then
		uci set network.wwan=interface
		uci set network.wwan.proto=dhcp  
		uci set network.wwan.metric="2"
		uci commit network
	fi

	/usr/lib/hotspot/travelmate.sh &
}
