#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Infinity >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Infinity=/luci-static/infinity
		set luci.main.mediaurlbase=/luci-static/infinity
		commit luci
	EOF
fi

exit 0
